# A basic task with a single step
apiVersion: tekton.dev/v1beta1
kind: Task
metadata: 
  name: hello
spec:
  steps:
    - name: say-hello
      image: registry.access.redhat.com/ubi8/ubi
      script: |
        #!/usr/bin/env bash
        echo Hello world