apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: read-file
spec:
  params: 
    - name: filename
      type: string
  workspaces:
    - name: files
  steps:
    - name: read
      image: registry.access.redhat.com/ubi8/ubi
      script: |
        #!/usr/bin/env bash
        echo "Reading from $(workspaces.files.path)/$(params.filename)"
        cd $(workspaces.files.path)
        cat $(params.filename)
---
# Use the git clone task from http://hub-preview.tekton.dev
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: read-from-git
spec:
  workspaces:
    - name: source
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "https://github.com/joellord/tekton-lab-sample.git"
      workspaces:
        - name: output
          workspace: source
    - name: read
      taskRef:
        name: read-file
      params: 
        - name: filename
          value: sample.txt
      workspaces:
        - name: files
          workspace: source
      runAfter:
        - clone-repo