# A basic task with multiple steps
# Shared folder between steps
apiVersion: tekton.dev/v1beta1
kind: Task
metadata: 
  name: hello
spec:
  params:
    - name: person
      type: string
      description: "Name of the person to say hello to"
      default: World
  steps:
    - name: write-name
      image: registry.access.redhat.com/ubi8/ubi
      script: |
        #!/usr/bin/env bash
        cd ~
        echo $(params.person) > name.txt
        echo "Name of person has been saved"
    - name: say-hello
      image: registry.access.redhat.com/ubi8/ubi
      script: |
        #!/usr/bin/env bash
        cd ~
        echo Hello $(cat ~/name.txt)